# Generated by Django 3.0.5 on 2020-06-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_Name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Date', models.DateField()),
                ('Poster', models.FileField(upload_to='')),
                ('Rules', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100)),
                ('Student_ProfilePic', models.FileField(upload_to='')),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Year', models.CharField(blank=True, max_length=5)),
                ('Address', models.CharField(blank=True, default='', max_length=100)),
                ('Contact', models.CharField(blank=True, default='+91-', max_length=10)),
                ('Audition_Video', models.FileField(blank=True, upload_to='')),
                ('Audition_Link', models.URLField(blank=True)),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Euphony.Branch')),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Euphony.Domain')),
                ('Event_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Euphony.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Euphony.Domain')),
                ('Year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Euphony.Register')),
            ],
        ),
    ]
