# Generated by Django 3.0.5 on 2020-06-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0002_branch_domain_events_register_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Contact',
            field=models.CharField(blank=True, default='+91-', max_length=14),
        ),
        migrations.AlterField(
            model_name='team',
            name='Year',
            field=models.CharField(default='', max_length=2),
        ),
    ]
