# Generated by Django 3.0.5 on 2020-06-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0004_auto_20200603_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
