# Generated by Django 3.0.5 on 2020-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0005_events_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='RollNo',
            field=models.CharField(blank=True, default='1702713031', max_length=12),
        ),
    ]
