# Generated by Django 3.0.5 on 2020-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0006_profile_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='FB_Link',
            field=models.CharField(blank=True, max_length=10000000),
        ),
        migrations.AddField(
            model_name='team',
            name='Insta_Link',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='team',
            name='Picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
