# Generated by Django 3.0.5 on 2020-06-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0007_auto_20200608_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.FileField(blank=True, upload_to='')),
                ('EventName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Euphony.Events')),
            ],
        ),
    ]
