# Generated by Django 3.0.5 on 2020-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0008_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='EventName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Picture',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
