# Generated by Django 3.0.5 on 2020-06-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0009_auto_20200609_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Branch',
        ),
        migrations.DeleteModel(
            name='EventForm',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
