# Generated by Django 3.0.5 on 2020-06-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Euphony', '0010_auto_20200610_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(blank=True, max_length=100)),
                ('Student_ProfilePic', models.FileField(upload_to='')),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=100)),
                ('Year', models.CharField(blank=True, max_length=5)),
                ('RollNo', models.CharField(blank=True, default='1702713031', max_length=12)),
                ('Address', models.CharField(blank=True, default='', max_length=100)),
                ('Contact', models.CharField(blank=True, default='+91-', max_length=14)),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Euphony.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audition_Video', models.FileField(blank=True, upload_to='')),
                ('Audition_Link', models.URLField(blank=True)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Euphony.Domain')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Euphony.Events')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Euphony.Profile')),
            ],
        ),
    ]
