# Generated by Django 3.0.5 on 2020-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0012_resets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Verified',
            field=models.CharField(blank=True, default='False', max_length=10),
        ),
    ]
