# Generated by Django 3.0.5 on 2020-06-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Euphony', '0013_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Contact', models.CharField(blank=True, max_length=100)),
                ('Reason', models.CharField(blank=True, max_length=10000)),
                ('Explanation', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
